import { StyleSheet } from 'react-native';

export const colors = {
  primary: '#667eea',
  secondary: '#764ba2',
  text: '#2d3748',
  muted: '#718096',
  bg: '#f7fafc',
  card: '#ffffff',
  border: '#e2e8f0',
  danger: '#e53e3e',
  success: '#38a169',
  warning: '#ed8936',
  cyan: '#38b2ac',
};

export const configStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  gradientPage: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 58,
    paddingBottom: 18,
    paddingHorizontal: 18,
    borderBottomLeftRadius: 26,
    borderBottomRightRadius: 26,
  },
  headerTitle: { flex: 1, color: '#fff', textAlign: 'center', fontSize: 20, fontWeight: '900' },
  backButton: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,0.18)' },
  backText: { fontSize: 26, color: '#fff', fontWeight: '900' },
  content: { padding: 16, paddingBottom: 38 },
  hero: { margin: 16, padding: 22, borderRadius: 24, backgroundColor: 'rgba(255,255,255,0.15)' },
  heroTitle: { color: '#fff', fontSize: 27, fontWeight: '900', marginBottom: 6 },
  heroSubtitle: { color: 'rgba(255,255,255,0.9)', fontSize: 14, lineHeight: 21 },
  mainGrid: { paddingHorizontal: 16, paddingBottom: 40 },
  menuCard: { backgroundColor: '#f7f7fb', borderRadius: 22, padding: 22, minHeight: 230, marginBottom: 18, shadowColor: '#000', shadowOpacity: 0.2, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  iconCircle: { width: 112, height: 112, borderRadius: 56, alignItems: 'center', justifyContent: 'center', alignSelf: 'center', marginBottom: 20, shadowColor: '#000', shadowOpacity: 0.18, shadowRadius: 16, shadowOffset: { width: 0, height: 8 }, elevation: 6 },
  iconText: { color: '#fff', fontSize: 48, fontWeight: '900' },
  rolePill: { position: 'absolute', top: 16, right: 16, paddingHorizontal: 13, paddingVertical: 7, borderRadius: 16, elevation: 4 },
  rolePillText: { color: '#fff', fontSize: 11, fontWeight: '900', letterSpacing: 0.5 },
  menuTitle: { fontSize: 22, color: colors.text, fontWeight: '900', marginBottom: 8 },
  menuDesc: { color: colors.muted, fontSize: 14, lineHeight: 21 },
  card: { backgroundColor: colors.card, borderRadius: 18, padding: 16, marginBottom: 14, shadowColor: '#000', shadowOpacity: 0.08, shadowRadius: 8, shadowOffset: { width: 0, height: 3 }, elevation: 3 },
  sectionBox: { backgroundColor: '#f8fafc', borderLeftWidth: 4, borderLeftColor: colors.primary, padding: 16, borderRadius: 18, marginBottom: 18 },
  cardTitle: { fontSize: 18, fontWeight: '900', color: colors.text, marginBottom: 5 },
  cardSubtitle: { fontSize: 13, color: colors.muted, lineHeight: 20 },
  sectionTitle: { fontSize: 19, fontWeight: '900', color: colors.text, marginBottom: 14, marginTop: 4 },
  subTitle: { fontSize: 17, fontWeight: '900', color: colors.primary, marginBottom: 14 },
  label: { fontSize: 13, fontWeight: '800', color: '#4a5568', marginBottom: 6, marginTop: 6 },
  input: { backgroundColor: '#fff', borderWidth: 1, borderColor: colors.border, borderRadius: 13, paddingHorizontal: 14, paddingVertical: 12, marginBottom: 10, color: colors.text, fontSize: 14 },
  inputMultiline: { minHeight: 88, textAlignVertical: 'top' },
  pickerBox: { backgroundColor: '#fff', borderWidth: 1, borderColor: colors.border, borderRadius: 13, marginBottom: 10, overflow: 'hidden' },
  row: { flexDirection: 'row', alignItems: 'center' },
  between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  primaryButton: { backgroundColor: colors.primary, paddingVertical: 14, borderRadius: 13, alignItems: 'center', justifyContent: 'center', marginTop: 8, flexDirection: 'row' },
  primaryText: { color: '#fff', fontSize: 15, fontWeight: '900' },
  secondaryButton: { backgroundColor: '#edf2f7', paddingVertical: 12, paddingHorizontal: 14, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  secondaryText: { color: '#4a5568', fontWeight: '900' },
  dangerButton: { backgroundColor: '#fff5f5', paddingVertical: 10, paddingHorizontal: 12, borderRadius: 10, borderWidth: 1, borderColor: '#fed7d7' },
  dangerText: { color: colors.danger, fontWeight: '900' },
  badge: { paddingHorizontal: 11, paddingVertical: 6, borderRadius: 14, backgroundColor: '#667eea20' },
  badgeText: { color: colors.primary, fontSize: 11, fontWeight: '900' },
  emptyText: { color: colors.muted, textAlign: 'center', paddingVertical: 20 },
  pagination: { marginTop: 10, marginBottom: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'center' },
  pageText: { marginHorizontal: 12, color: '#475569', fontWeight: '900' },
  smallIconButton: { width: 40, height: 40, borderRadius: 13, backgroundColor: '#eef2ff', alignItems: 'center', justifyContent: 'center' },
  actionBar: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 12, marginTop: 10 },
});
