import { Platform, StyleSheet } from 'react-native';

export const colors = {
  primary: '#667eea',
  secondary: '#764ba2',
  text: '#2d3748',
  muted: '#718096',
  bg: '#f7fafc',
  card: '#ffffff',
  border: '#e2e8f0',
  danger: '#e53e3e',
  success: '#38a169',
  warning: '#ed8936',
  cyan: '#38b2ac',
  softPrimary: '#eef2ff',
};

const cardShadow = Platform.select({
  ios: {
    shadowColor: '#2d3748',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.09,
    shadowRadius: 8,
  },
  android: { elevation: 3 },
  default: {
    shadowColor: '#2d3748',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.09,
    shadowRadius: 8,
  },
});

export const configStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  gradientPage: { flex: 1, backgroundColor: colors.bg },

  header: {
    minHeight: 132,
    paddingTop: 54,
    paddingBottom: 22,
    paddingHorizontal: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },
  headerTitle: {
    flex: 1,
    color: '#fff',
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '800',
    paddingHorizontal: 10,
  },
  backButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.16)',
  },
  backText: { fontSize: 26, color: '#fff', fontWeight: '700', marginTop: -2 },

  content: { paddingHorizontal: 16, paddingTop: 18, paddingBottom: 44 },
  hero: {
    paddingTop: 56,
    paddingBottom: 48,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
  },
  heroTitle: { color: '#fff', fontSize: 26, fontWeight: '800', marginBottom: 6 },
  heroSubtitle: {
    color: 'rgba(255,255,255,0.86)',
    fontSize: 14,
    lineHeight: 20,
    maxWidth: 620,
  },

  mainGrid: {
    paddingHorizontal: 12,
    paddingTop: 18,
    paddingBottom: 44,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  menuCard: {
    backgroundColor: '#fff',
    borderRadius: 18,
    padding: 16,
    minHeight: 176,
    marginHorizontal: '1%',
    marginBottom: 12,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    borderWidth: 1,
    borderColor: '#edf0f7',
    ...cardShadow,
  },
  iconCircle: {
    width: 62,
    height: 62,
    borderRadius: 31,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  iconText: { color: '#fff', fontSize: 28, fontWeight: '800' },
  rolePill: {
    position: 'absolute',
    top: 10,
    right: 10,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  rolePillText: { color: '#fff', fontSize: 9, fontWeight: '800', letterSpacing: 0.3 },
  menuTitle: {
    fontSize: 15,
    color: colors.text,
    fontWeight: '800',
    marginBottom: 5,
    textAlign: 'center',
  },
  menuDesc: {
    color: colors.muted,
    fontSize: 11,
    lineHeight: 16,
    textAlign: 'center',
  },

  card: {
    backgroundColor: colors.card,
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#edf0f7',
    ...cardShadow,
  },
  sectionBox: {
    backgroundColor: '#fff',
    borderLeftWidth: 4,
    borderLeftColor: colors.primary,
    padding: 16,
    borderRadius: 16,
    marginBottom: 16,
    ...cardShadow,
  },
  cardTitle: { fontSize: 16, fontWeight: '800', color: colors.text, marginBottom: 4 },
  cardSubtitle: { fontSize: 12, color: colors.muted, lineHeight: 18 },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: colors.text,
    marginBottom: 12,
    marginTop: 8,
  },
  subTitle: { fontSize: 15, fontWeight: '800', color: colors.primary, marginBottom: 12 },
  sectionHeadingRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 14 },
  sectionIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.softPrimary,
    marginRight: 10,
  },
  sectionHeadingText: { flex: 1 },

  label: {
    fontSize: 12,
    fontWeight: '700',
    color: '#4a5568',
    marginBottom: 6,
    marginTop: 4,
  },
  input: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    minHeight: 48,
    paddingHorizontal: 14,
    paddingVertical: 11,
    marginBottom: 12,
    color: colors.text,
    fontSize: 14,
  },
  inputMultiline: { minHeight: 92, textAlignVertical: 'top' },
  pickerBox: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    marginBottom: 12,
    overflow: 'hidden',
  },
  row: { flexDirection: 'row', alignItems: 'center' },
  between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },

  primaryButton: {
    backgroundColor: colors.primary,
    minHeight: 50,
    paddingHorizontal: 18,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 8,
    flexDirection: 'row',
  },
  primaryText: { color: '#fff', fontSize: 14, fontWeight: '800' },
  secondaryButton: {
    backgroundColor: colors.softPrimary,
    minHeight: 44,
    paddingHorizontal: 14,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  secondaryText: { color: '#4c51bf', fontWeight: '800' },
  dangerButton: {
    backgroundColor: '#fff5f5',
    minHeight: 42,
    paddingHorizontal: 12,
    borderRadius: 11,
    borderWidth: 1,
    borderColor: '#fed7d7',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dangerText: { color: colors.danger, fontWeight: '800' },

  badge: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 14, backgroundColor: '#667eea20' },
  badgeText: { color: colors.primary, fontSize: 10, fontWeight: '800' },
  emptyText: { color: colors.muted, textAlign: 'center', paddingVertical: 22, fontSize: 13 },
  pagination: {
    marginTop: 10,
    marginBottom: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pageText: { marginHorizontal: 12, color: '#475569', fontWeight: '800' },
  smallIconButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: colors.softPrimary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionBar: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 10, marginTop: 10 },
  wrapRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 },
  optionChip: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 18,
  },
  optionChipActive: { borderColor: colors.primary, backgroundColor: colors.softPrimary },
  optionText: { color: colors.muted, fontSize: 12, fontWeight: '700' },
  optionTextActive: { color: colors.primary },
  messageBox: { backgroundColor: colors.softPrimary, borderRadius: 12, padding: 12, marginVertical: 10 },
  messageText: { color: '#4338ca', fontSize: 12, lineHeight: 18, fontWeight: '700' },
  searchInput: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    minHeight: 48,
    paddingHorizontal: 14,
    paddingVertical: 11,
    marginBottom: 16,
  },
  disabled: { opacity: 0.5 },
});
